### ISSUE TITLE
make build is not working after create project using composer and other things in Makefile

### ISSUE THREAD

**Issue by acidber** [CodelyTV/php-ddd-skeleton#17]
https://github.com/CodelyTV/php-ddd-skeleton/blob/d67e903ddbc3f01d888bd636ea715387667aea32/Makefile#L14

Start server using docker with `make build` is not working after create a new project using composer `composer create-project codelytv/ddd-skeleton`.

The problem is that gsingh1/prestissimo image was removed. You fixed this changing it to clevyr/prestissimo image but it seems that composer is not taking last version.

After talk with @JavierCane it seems that the problem is that composer is not taking master branch, is taking last known tag which contains old image.

https://github.com/CodelyTV/php-ddd-skeleton/blob/d67e903ddbc3f01d888bd636ea715387667aea32/Makefile#L1
By the way, I think that this line it would be `.phony` instead of `.pony`, isn't it?

https://github.com/CodelyTV/php-ddd-skeleton/blob/d67e903ddbc3f01d888bd636ea715387667aea32/Makefile#L38

It shouldn't be `doco` here instead of `doco start stop destroy`?

Sorry if I'm wrong.

**Comment by JavierCane** [comment]
Thanks for the report!

We'll take a look and release new tags 🙂

**Comment by JavierCane** [comment]
[Version `1.0.0` released](https://github.com/CodelyTV/php-ddd-skeleton/releases/tag/1.0.0). This implies that a new tag `1.0.0` has been created pointing to the latest commit where this issue was solved.

Now you can execute again the `composer create-project codelytv/ddd-skeleton` command and Composer will take into account this latest tag 🤟
